# Main config file configuration
imports:
    - { resource: ../common/config.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: routing.yml }